// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConn(arg1) {
  return window['go']['backend']['DbService']['AddConn'](arg1);
}

export function AddTopic(arg1) {
  return window['go']['backend']['DbService']['AddTopic'](arg1);
}

export function CreateClient(arg1) {
  return window['go']['backend']['DbService']['CreateClient'](arg1);
}

export function CreateConsumer(arg1) {
  return window['go']['backend']['DbService']['CreateConsumer'](arg1);
}

export function CreateProducer(arg1) {
  return window['go']['backend']['DbService']['CreateProducer'](arg1);
}

export function DelTopic(arg1) {
  return window['go']['backend']['DbService']['DelTopic'](arg1);
}

export function DeleteConn(arg1) {
  return window['go']['backend']['DbService']['DeleteConn'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['backend']['DbService']['Disconnect'](arg1);
}

export function QueryByTopic(arg1) {
  return window['go']['backend']['DbService']['QueryByTopic'](arg1);
}

export function QueryConfigs() {
  return window['go']['backend']['DbService']['QueryConfigs']();
}

export function QueryConns() {
  return window['go']['backend']['DbService']['QueryConns']();
}

export function QueryTopics(arg1) {
  return window['go']['backend']['DbService']['QueryTopics'](arg1);
}

export function Receive(arg1) {
  return window['go']['backend']['DbService']['Receive'](arg1);
}

export function RemoveConsumer(arg1) {
  return window['go']['backend']['DbService']['RemoveConsumer'](arg1);
}

export function RemoveProducer(arg1) {
  return window['go']['backend']['DbService']['RemoveProducer'](arg1);
}

export function SendMsg(arg1) {
  return window['go']['backend']['DbService']['SendMsg'](arg1);
}

export function Shutdown() {
  return window['go']['backend']['DbService']['Shutdown']();
}

export function Startup(arg1) {
  return window['go']['backend']['DbService']['Startup'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['backend']['DbService']['UpdateConfig'](arg1);
}
