// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend, context} from '../models';

export function AddConn(arg1:backend.Conn):Promise<void>;

export function AddTopic(arg1:backend.Topic):Promise<void>;

export function CreateClient(arg1:backend.Conn):Promise<void>;

export function CreateConsumer(arg1:backend.Topic):Promise<void>;

export function CreateProducer(arg1:backend.Topic):Promise<void>;

export function DelTopic(arg1:number):Promise<void>;

export function DeleteConn(arg1:number):Promise<void>;

export function Disconnect(arg1:number):Promise<void>;

export function QueryByTopic(arg1:number):Promise<Array<backend.Msg>>;

export function QueryConfigs():Promise<Array<backend.Config>>;

export function QueryConns():Promise<Array<backend.Conn>>;

export function QueryTopics(arg1:number):Promise<Array<backend.Topic>>;

export function Receive(arg1:number):Promise<void>;

export function RemoveConsumer(arg1:number):Promise<void>;

export function RemoveProducer(arg1:number):Promise<void>;

export function SendMsg(arg1:backend.Msg):Promise<void>;

export function Shutdown():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateConfig(arg1:backend.Config):Promise<void>;
